from elasticsearch import Elasticsearch
import os
import json
from dotenv import load_dotenv
load_dotenv()

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = os.environ.get("ELASTIC_PASSWORD")

# Create the client instance
client = Elasticsearch(
    hosts=["https://localhost:9200"],
    verify_certs=False, # TODO: Add links to certs
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

def create_index(index_name):
    with open("srt/utils/mapping.json") as f:
        mapping_body = json.load(f)
    client.indices.create(index=index_name, body=mapping_body)

def delete_index(index_name):
    client.indices.delete(index=index_name)

def index_data(index_name, data):
    client.index(index=index_name, document=data, refresh=True)

def search_data(index_name, data):
    client.search(index=index_name, body=data)
